### ISSUE TITLE
Scenario output not being rendered to HTML template

### ISSUE THREAD

**Issue by kevbradwick** [DonutReport/donut#55]
The latest version of Cinnamon (0.2.0) uses a newer version of Cucumber (4.2.6). The `cucumber.json` file that gets generated puts any output (when using `Scenario.write` within an after hook) into the json structure `elements.[index].after.[index].output`. Donut does not output this custom output as it is looking in the older location of `elements.[index].steps.[index].output` which was in the older version of Cucumber (with Cinnamon 0.1.2).

See https://github.com/DonutReport/donut/blob/master/src/main/scala/report/donut/gherkin/processors/HTMLProcessor.scala#L157

and

https://github.com/DonutReport/donut/blob/master/src/main/scala/report/donut/gherkin/processors/HTMLProcessor.scala#L107

We rely on the after hooks to write custom output when a scenario fails and can no longer see this output with the latest Cinnamon/Cucumber. This issue probably extends to writing to scenarios in before hook too (but haven't checked).

**Comment by davebassan** [comment]
Hi Kevin, we'll look into this and get a new release out a.s.a.p

**Comment by davebassan** [comment]
I have just released 1.2.2 that fixes this issue.
